---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian-stretch-builder
    image: "quay.io/freedomofpress/debian-stretch-builder@sha256:{{ image_hash }}"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
