#!/usr/bin/python

import sys
from PyQt4 import QtGui

def main():
    app = QtGui.QApplication(sys.argv)
    w = QtGui.QWidget()

    QtGui.QMessageBox.warning(w, "Please do not open here",
     "Please do not use this VM for opening files other than those downloaded from the SecureDrop Journalist interface.")

    sys.exit()

if __name__ == '__main__':
    main()
