#!/usr/bin/env python3

import errno
import posix
import sys
import os

arg = sys.stdin.readline().encode('utf-8')

try:
    fifo = os.open('/home/user/sdfifo', posix.O_WRONLY | posix.O_NONBLOCK)
    os.write(fifo, arg)
except OSError as ex:
    if ex.errno == errno.ENXIO:
        pass
