#!/usr/bin/env python

import sys
import subprocess
import os

fn = sys.argv[1]

# TODO: pull this in to a library... XXX
def send_progress(msg):
    p = subprocess.Popen(["qrexec-client-vm", "sd-journalist",
                         "sd-process.Feedback"],
                         close_fds=True,
                         stdin=subprocess.PIPE)
    p.communicate(msg)

send_progress("DECRYPTED_BUNDLE_ON_SVS")

try:
    cmd = ["tar", "-xf", fn,
           "--strip-components=2", "-C", "/home/user/Sources"]
    res = subprocess.call(cmd)
    if res != 0:
        send_progress("DECRYPTED_BUNDLE_UNBUNDLE_ERROR")
        sys.exit(1)
except Exception as e:
    send_progress("DECRYPTED_BUNDLE_UNBUNDLE_ERROR")
    sys.exit(2)

send_progress("DECRYPTED_FILES_AVAILABLE")

os.unlink(fn)
