#!/usr/bin/env python

import sys
import subprocess
import os

input = sys.argv[1]

print input

subprocess.call(["tar", "-xvf", input, "--strip-components=2", "-C", "/home/user/Sources"])

os.unlink(input)
