#!/usr/bin/bash

# udev action for attaching USB export devices sd-devices or sd-printers

ATTACH_TARGET_QUBE="$1"

QDEVNAME="$(basename "$DEVPATH")"
echo sys-usb "$QDEVNAME" | qrexec-client-vm "$ATTACH_TARGET_QUBE" qubes.USBAttach
