#!/bin/bash
# Builds RPMs for installation in dom0. RPMs are fully reproducible.
# Targets fedora-25 & fedora-32 for Qubes 4.0 and 4.1 support.
set -e
set -u
set -o pipefail


# Check for dependencies
if ! hash rpmbuild 2> /dev/null ; then
    echo "ERROR: missing rpmbuild, run: make install-deps"
    exit 1
fi

# Prepare tarball, rpmbuild will use it
mkdir -p dist/
git clean -fdX rpm-build/ dist/
/usr/bin/python3 setup.py sdist

# Use the epoch time of the highest semver tag available.
# SOURCE_DATE_EPOCH="$(git tag | sort -V | tail -n 1 | xargs git log -1 --format=%at)"
# Use the epoch time of the most recent commit. If works in dev,
# as well as building from signed tags.
SOURCE_DATE_EPOCH="$(git log -1 --format=%at HEAD)"
export SOURCE_DATE_EPOCH

# Place tarball where rpmbuild will find it
cp dist/*.tar.gz rpm-build/SOURCES/

python_version="python3.8"
dist=".fc32"
rpmbuild \
    --quiet \
    --define "_topdir $PWD/rpm-build" \
    --define "dist $dist" \
    --define "_python_version $python_version" \
    -bb --clean "rpm-build/SPECS/securedrop-workstation-dom0-config.spec"

printf '\nBuild complete! RPMs and their checksums are:\n\n'
find rpm-build/ -type f -iname '*.rpm' -print0 | sort -zV | xargs -0 sha256sum
