#!/usr/bin/bash
# Utility to copy workstation config files from target AppVM
# to dom0, for use in testing the salt logic for VM configuration.
# Should only be run in dom0!
set -e
set -u
set -o pipefail

source "$(dirname "$0")/common.sh"

# Ensure we're running in dom0, otherwise clone action could destroy
# active work in AppVM.
if [[ "$(hostname)" != "dom0" ]]; then
    echo 'Clone action must be run from dom0!'
    exit 1
fi

# Call out to target AppVM, to build RPMs for dom0. The RPMs will be included
# in the subsequent tarball, which is fetched to dom0.
function build-dom0-rpm() {
    printf "Building RPM on %s ...\n" "${DEV_VM}"
    dom0_fedora_version="$(rpm --eval '%{fedora}')"
    qvm-run --pass-io "$DEV_VM" "FEDORA_VERSION=$dom0_fedora_version make -C $DEV_DIR build-rpm"
}

# Call out to target AppVM to create a tarball in dom0
function create-tarball() {
    printf "Cloning code from %s:%s ...\n" "${DEV_VM}" "${DEV_DIR}"
    qvm-run --pass-io "$DEV_VM" \
        "tar -c --exclude-vcs \
        -C '$(dirname "$DEV_DIR")' \
        '$(basename "$DEV_DIR")'" > /tmp/sd-proj.tar
}

function unpack-tarball() {
    rm -rf "${DOM0_DEV_DIR:?}/"*
    tar xf /tmp/sd-proj.tar -C "${DOM0_DEV_DIR}" --strip-components=1
}

# By default we build the RPMs, but the step can be skipped, which is useful
# for certain development tasks
if [[ "${BUILD_RPM:-true}" == "true" ]]; then
  build-dom0-rpm
fi

create-tarball
unpack-tarball
