#!/usr/bin/env python3
"""
Helper script to permit developers to select deployment
strategies for the dom0-based SecureDrop Workstation config.

Updates the config.json in-place in dom0 in order to modify.
"""
import json
import sys
import argparse
import os


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        default="config.json",
        required=False,
        action="store",
        help="Path to JSON configuration file",
    )
    parser.add_argument(
        "--environment",
        default="prod",
        required=False,
        action="store",
        help="Target deploy strategy, e.g. 'prod', 'dev', or 'staging'",
    )
    args = parser.parse_args()
    if not os.path.exists(args.config):
        msg = "Config file not found: {}\n".format(args.config)
        sys.stderr.write(msg)
        parser.print_help(sys.stderr)
        sys.exit(1)

    if args.environment not in ("prod", "dev", "staging"):
        parser.print_help(sys.stderr)
        sys.exit(2)
    return args


def set_env_in_config(args):
    with open(args.config, 'r') as f:
        old_config = json.load(f)

    new_config = dict(old_config)
    new_config["environment"] = args.environment

    if new_config != old_config:
        msg = "Updated config environment to '{}'...\n".format(args.environment)
        sys.stderr.write(msg)

        with open(args.config, 'w') as f:
            json.dump(new_config, f)


if __name__ == "__main__":
    args = parse_args()
    set_env_in_config(args)
