#!/bin/bash
set -e
set -u
set -o pipefail


# Install 'file', used for discovering all Python scripts.
# This is a hack, we should fold in the 'file' package as a dependecy
# in the underlying container.
printf "Updating apt lists..."
apt-get update > /dev/null
printf " done.\n"

apt-get install -qq file

# Install flake8 inside container
pip install -q flake8

# First pass with flake8 autodiscovery
flake8

# Second pass to make sure we've found all Python scripts,
# since flake8's autodiscovery option can miss some.
find -type f -exec file -i {} + \
  | perl -F':\s+' -nE '$F[1] =~ m/text\/x-python/ and say $F[0]' \
  | xargs flake8
