#!/bin/bash
set -e
set -u
set -o pipefail

if ! [ -x "$(command -v file)" ]; then
  echo "Error: file is not installed."  >&2
  echo >&2
  echo "The file command is required to enumerate all Python files in this repo." >&2
  echo "On Debian/Ubuntu systems, run the following command to install it:" >&2
  echo >&2
  echo "  sudo apt-get install file" >&2
  exit 1
fi

if [ -z "$@" ]; then
    echo "Usage: lint-all <command>"
    echo
    echo "lint-all: Run a linter against all Python files in the repository"
    echo
    echo "Example:"
    echo "   lint-all \"flake8 --max-line-length=100\""
    exit 1
fi

# Because this repo contains some files without the .py file extension, we
# scan all directories except for the ones specified in the first line for
# files which
#
# - the file command recognizes as the MIME type "text/x-python", OR
# - which are identified as Python by their file extension, and recognized as
#   plain text by the file command.
#
# In practice, this gives us full coverage of Pyhton files in this repository
# without having to manually update a list of special cases.
find . -type d \( -name .venv -o -name .git -o -name rpm-build \) \
  -prune -o \
  -type f -exec file --mime-type {} + | \
  grep -E '(text/x-python$|^.*\.py:\s*text/plain$)' | \
  cut -d: -f1 | \
  xargs $@
