#!/bin/bash
set -e
set -u
set -o pipefail


if [ -z "$@" ]; then
    echo "Usage: lint-all <command>"
    echo
    echo "lint-all: Run a linter against all Python files in the repository"
    echo
    echo "Example:"
    echo "   lint-all \"flake8 --max-line-length=100\""
    exit 1
fi

# Because this repo contains some files without the .py file extension, we
# scan all directories except for the ones specified in the first line for
# files which
#
# - the file command recognizes as the MIME type "text/x-python", OR
# - which are identified as Python by their file extension, and recognized as
#   plain text by the file command.
#
# In practice, this gives us full coverage of Pyhton files in this repository
# without having to manually update a list of special cases.
find . -type d \( -name .venv -o -name .git -o -name rpm-build \) \
  -prune -o \
  -type f -exec file --mime-type {} + | \
  grep -E '(text/x-python$|^.*\.py:\s*text/plain$)' | \
  cut -d: -f1 | \
  xargs $@
