#!/bin/bash
# Prints names of all Salt-managed Workstation VMs.
# Intended for use with other actions, e.g. destroy-all.
set -e
set -u
set -o pipefail


declare -a sd_workstation_vm_names=(
  sd-gpg
  sd-proxy
  sd-proxy-template
  sd-svs
  sd-svs-template
  securedrop-workstation
  sd-whonix
  sd-svs-disp
  sd-svs-disp-template
  sd-export-template
  sd-export-dvm
  sd-export
)

for vm in "${sd_workstation_vm_names[@]}" ; do
    echo "$vm"
done
