#!/bin/bash
# Prints names of all Salt-managed Workstation VMs.
# Intended for use with other actions, e.g. destroy-all.
set -e
set -u
set -o pipefail

declare -a sd_workstation_vm_names=(
  sd-gpg
  sd-journalist
  sd-journalist-template
  sd-svs
  sd-svs-template
  sd-workstation-template
  sd-whonix
  sd-whonix-template
  sd-svs-disp
  sd-svs-disp-template
)

for vm in "${sd_workstation_vm_names[@]}" ; do
    echo "$vm"
done
