#!/bin/bash
# Developer-oriented utility script for deploying Saltstack config
# files for the SecureDrop Workstation dev env.
set -e
set -u
set -o pipefail


# Hardcoded location of SecureDrop Workstation salt config files
SDW_SALT_DIR="/srv/salt/sd"


echo "Deploying Salt config..."

# If SDW Salt config dir already exists, don't overwrite contents.
# Avoiding clobbering allows testing of the dom0 config package.
# Use `make clean` to trigger redeployment of these files.
if [[ ! -d "$SDW_SALT_DIR" ]]; then
    sudo mkdir -p /srv/salt/sd
    sudo cp -r sd-proxy /srv/salt/sd
    sudo cp -r sd-svs /srv/salt/sd
    sudo cp -r sd-whonix /srv/salt/sd
    sudo cp -r sd-workstation /srv/salt/sd
    sudo cp -r sys-firewall /srv/salt/sd
    sudo cp dom0/* /srv/salt/
fi

# Always copy secrets, these won't be configured as part
# of the RPM installation.
sudo cp config.json /srv/salt/sd
sudo cp sd-journalist.sec /srv/salt/sd

# Enable top files, otherwise qubesctl will report "nothing to do".
sudo find /srv/salt -maxdepth 1 -type f -iname '*.top' \
    | xargs -n1 basename \
    | sed -e 's/\.top$//g' \
    | xargs sudo qubesctl top.enable
