#!/bin/bash
#
#
# Builds RPM for dom0 bootstrap logic
# $1 - Digest Hash of base docker container to use

set -u
set -e

export CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

. "${CUR_DIR}/rpm-docker-source"

docker_cmd_wrapper /usr/bin/python3 setup.py sdist

docker_cmd_wrapper rpmbuild -ba "${USER_RPMDIR}/SPECS/securedrop-workstation.spec"

printf "\n\nRPM Artifacts available in ./artifacts RPMS and SRPMS sub-directories\n"
