#!/bin/bash
# Utility to update the default Fedora templates used by Qubes
# when creating other VMs.
set -e
set -u
set -o pipefail


# Install the Qubes-maintained Fedora template if absent.
# We must use conditional logic, since the update command
# will fail if the package is already installed.
if ! rpm -qa | grep -q ^qubes-template-fedora-28 ; then
    sudo qubes-dom0-update qubes-template-fedora-28
fi

# Check whether a suitable DispVM exists.
if ! qvm-ls --quiet fedora-28-dvm 2&>1 > /dev/null ; then
    qvm-create --template fedora-28 --class DispVM --label red fedora-28-dvm
fi

# Set latest Fedora as the default DispVM throughout.
sudo qubes-prefs default_template fedora-28
sudo qubesctl state.sls qvm.default-dispvm
qubes-prefs default_dispvm fedora-28-dvm
