#!/bin/bash
# Utility to update the default Whonix templates used by Qubes
# when creating other VMs.
set -e
set -u
set -o pipefail


# Install the Community-maintained Whonix 14 templates (gw and ws) if absent.
# We must use conditional logic, since the update command
# will fail if the package is already installed.
if ! rpm -qa | grep -q ^qubes-template-whonix-ws-14 ; then
    sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-whonix-ws-14
fi

if ! rpm -qa | grep -q ^qubes-template-whonix-gw-14 ; then
    sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-whonix-gw-14
fi
