#!/bin/bash
# Wrapper script to manage the TemplateVM build process.
# Clones the qubes-builder repo, as well as the securedrop-workstation repo,
# and generates an RPM that can be installed in dom0 to support new TemplateVMs.
set -e
set -u
set -o pipefail

repo_root="$(git rev-parse --show-toplevel)"
build_dir="${repo_root}/builder"
qubes_builder_dir="${build_dir}/qubes-builder"
sd_template_dir="${build_dir}/qubes-template-securedrop-workstation"

# Chroot may exist due to previous failed build; let's clean up responsibly.
if [[ -d "${qubes_builder_dir}" ]]
then
    # Command exits 0 even if no chroot exists.
    make -C "${qubes_builder_dir}" clean-chroot
fi

# Heavy-handed, but ensures build is clean, and also sidesteps idempotence
# issues with the git clone/checkout commands.
rm -rf "${qubes_builder_dir}" "${sd_template_dir}"

git clone https://github.com/qubesos/qubes-builder "${build_dir}/qubes-builder"
git clone https://github.com/freedomofpress/qubes-template-securedrop-workstation "${sd_template_dir}"

cd "${qubes_builder_dir}"

# Provision securedrop-workstation config so that we get the correct sources via `make get-sources`.
cp ${sd_template_dir}/securedrop-workstation.conf builder.conf

# Install dependencies from Qubes builder logic.
make install-deps
make get-sources

# Build it!
make qubes-vm
make template
