#!/bin/bash
# Wrapper script to manage the TemplateVM build process.
# Clones the qubes-builder repo, as well as the securedrop-workstation repo,
# and generates an RPM that can be installed in dom0 to support new TemplateVMs.
set -e
set -u
set -o pipefail

repo_root="$(git rev-parse --show-toplevel)"
build_dir="${repo_root}/builder"
qubes_builder_dir="${build_dir}/qubes-builder"
sd_template_dir="${build_dir}/qubes-template-securedrop-workstation"
gpg_homedir="${repo_root}/builder/qubes-builder/keyrings/git"

# Chroot may exist due to previous failed build; let's clean up responsibly.
if [[ -d "${qubes_builder_dir}" ]]
then
    # Command exits 0 even if no chroot exists.
    make -C "${qubes_builder_dir}" clean-chroot
fi

# Heavy-handed, but ensures build is clean, and also sidesteps idempotence
# issues with the git clone/checkout commands.
rm -rf "${qubes_builder_dir}" "${sd_template_dir}"

git clone https://github.com/qubesos/qubes-builder "${build_dir}/qubes-builder"
git clone https://github.com/freedomofpress/qubes-template-securedrop-workstation "${sd_template_dir}"

cd "${qubes_builder_dir}"

# Provision securedrop-workstation config so that we get the correct sources via `make get-sources`.
cp ${sd_template_dir}/securedrop-workstation.conf builder.conf

# Get sources for only the builder component, which will get Qubes dev keys and initialize the keyring
make COMPONENTS="builder" get-sources

# Add signing key to the keyring
gpg --homedir ${gpg_homedir} --keyserver pool.sks-keyservers.net --recv-key AF775782949D263DAABB3387AAFB3575FAC82745 || exit 1;
echo 'AF775782949D263DAABB3387AAFB3575FAC82745:6:' | gpg --homedir ${gpg_homedir} --import-ownertrust;

# Get all sources
make get-sources

# Install dependencies from Qubes builder logic.
make install-deps

# Build it!
make qubes-vm
make template

# Report location of RPM package
rpm_location="$(sudo find -type f -name 'qubes-template-securedrop-workstation*.rpm')"
echo "Build finished. RPM package available at:"
echo "$rpm_location"
