#!/bin/bash

set -e
set -u
set -o pipefail

TASK=${1:-default}

# To allow the template of an AppVM to be changed, the following two
# conditions must be met:
# 1. The AppVM must be powered off
# 2. The AppVM must not be a DispVM template that used as the default DispVM
#    for an AppVM, nor the system default DispVM.
if [[ $TASK == "prepare" ]]; then
    # sd-app, we simply shutdown the machine as we want to preserve the data
    if qvm-check sd-app --quiet; then
        BASE_TEMPLATE=$(qvm-prefs sd-app template)
        if [[ ! $BASE_TEMPLATE =~ "small-buster" ]]; then
            if qvm-check --running sd-app; then
                qvm-shutdown --wait sd-app
            fi
        fi
    fi

    # For sd-viewer and sd-devices-dvm, DispVM templates. We can delete both
    # VMs since they contain no persistent data. The installer will re-create them
    # as part of the provisioning process.
    # We set the default DispVM to empty string to ensure nothing is opened in an
    # insecure (unmanaged or not yet updated) or networked vm, until the
    # provisioning process runs again and sets that value to sd-viewer
    if qvm-check --quiet sd-viewer; then
        BASE_TEMPLATE=$(qvm-prefs sd-viewer template)
        if [[ ! $BASE_TEMPLATE =~ "large-buster" ]]; then
            qubes-prefs default_dispvm ''
            qvm-shutdown --wait sd-viewer
            qvm-remove -f sd-viewer
        fi
    fi

    if qvm-check --quiet sd-devices; then
        BASE_TEMPLATE=$(qvm-prefs sd-devices-dvm template)
        if [[ ! $BASE_TEMPLATE =~ "large-buster" ]]; then
            qvm-shutdown --wait sd-devices
            qvm-shutdown --wait sd-devices-dvm
            qvm-remove -f sd-devices
            qvm-remove -f sd-devices-dvm
        fi
    fi

    # For Whonix VMs, shut them down, so we can upate the TemplateVM settings.
    # We shut down sd-proxy before sd-whonix, since its netvm is sd-whonix, which won't
    # shutdown if a client is connected.
    if qvm-check --quiet sd-proxy; then
        BASE_TEMPLATE=$(qvm-prefs sd-proxy template)
        if [[ ! $BASE_TEMPLATE =~ "large-buster" ]]; then
            qvm-shutdown --wait sd-proxy
        fi
    fi

    # for sd-whonix, we must make sure sd-proxy is shut down as well as sd-whonix
    # is netvm for sd-proxy. In the unlikely even proxy is updated but whonix
    # is not, we want to ensure a smooth upgrade.
    if qvm-check --quiet sd-whonix; then
        BASE_TEMPLATE=$(qvm-prefs sd-whonix template)
        if [[ ! $BASE_TEMPLATE =~ "15" ]]; then
            qvm-shutdown --wait sd-proxy
            qvm-shutdown --wait sd-whonix
        fi
    fi

    # Kill sys-whonix, to make sure connected clients don't prevent shutdown.
    if qvm-check --quiet sys-whonix; then
        BASE_TEMPLATE=$(qvm-prefs sys-whonix template)
        if [[ ! $BASE_TEMPLATE =~ "15" ]]; then
            if qvm-check --quiet --running sys-whonix; then
                qvm-kill sys-whonix
                # Wait for machine to stop fully, since qvm-kill doesn't block
                sleep 5
            fi
        fi
    fi

    # For sd-gpg, we simply shutdown the machine
    if qvm-check --quiet sd-gpg; then
        BASE_TEMPLATE=$(qvm-prefs sd-gpg template)
        if [[ ! $BASE_TEMPLATE =~ "small-buster" ]]; then
            qvm-shutdown --wait sd-gpg
        fi
    fi

    # Shut down sd-log last, since other VMs will autostart it by sending logs
    if qvm-check --quiet sd-log; then
        BASE_TEMPLATE=$(qvm-prefs sd-log template)
        if [[ ! $BASE_TEMPLATE =~ "small-buster" ]]; then
            qvm-shutdown --wait sd-log
        fi
    fi
elif [[ $TASK == "remove" ]]; then
    # For each template, ensure the TemplateVM exists, that it is shut down
    # before deleting it.
    for template in sd-app-template sd-viewer-template sd-devices-template sd-proxy-template
    do
        if qvm-check "${template}" --quiet; then
            if qvm-check --running "${template}"; then
                qvm-shutdown --wait "${template}"
            fi
            qvm-remove -f "${template}"
        fi
    done
else
    echo "Please specify prepare or remove"
    exit 1
fi
