# Type stubs for the `qubesadmin.app` module.
from collections.abc import Iterator

from qubesadmin.vm import QubesVM

class VMCollection:
    def __iter__(self) -> Iterator[QubesVM]: ...
    def __getitem__(self, key: str | QubesVM) -> QubesVM: ...
    def __contains__(self, key: object) -> bool: ...
    def get(self, key: str, default: QubesVM | None = ...) -> QubesVM | None: ...
