# Type stubs for the `qubesadmin.vm` package.
from collections.abc import Iterable, Iterator, Mapping
from typing import TypeVar, overload

_T = TypeVar("_T")

class Tags:
    def __contains__(self, tag: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def add(self, tag: str) -> None: ...
    def discard(self, tag: str) -> None: ...
    def remove(self, tag: str) -> None: ...
    def update(self, tags: Iterable[str]) -> None: ...

class Features:
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    @overload
    def get(self, key: str) -> str | None: ...
    @overload
    def get(self, key: str, default: _T) -> str | _T: ...

class Volume:
    name: str
    size: int

class QubesVM:
    name: str
    klass: str
    tags: Tags
    features: Features
    volumes: Mapping[str, Volume]
    template: QubesVM
    netvm: QubesVM | None
    default_dispvm: QubesVM | None
    virt_mode: str
    kernel: str
    autostart: bool
    provides_network: bool
    template_for_dispvms: bool
    installed_by_rpm: bool
    is_preload: bool
    auto_cleanup: bool
    appvms: Iterable[QubesVM]
    derived_vms: Iterable[QubesVM]
    def is_running(self) -> bool: ...
    def is_halted(self) -> bool: ...
    def start(self) -> None: ...
    def shutdown(self) -> None: ...
    def kill(self) -> None: ...
    def property_is_default(self, name: str) -> bool: ...
    # Returns (stdout, stderr) from a qrexec call into the VM.
    def run(self, command: str, user: str | None = ...) -> tuple[bytes, bytes]: ...
